CLASS zstock_fill DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zstock_fill IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
  DATA: stock_full_data TYPE TABLE OF zstock_data_fin.

    stock_full_data = VALUE #(
            ( zstock_ticker = 'LON:CSPX' zstock_name = 'iShares Core S&P 500 UCITS ETF USD (Acc)' zstock_price = '765.96' zstock_changepct = '-0.0036' zstock_priceopen = '769.77' zstock_currency = 'USD' zstock_closeyest = '768.7' zstock_high = '770.66' )
            ( zstock_ticker = 'AMS:VWCE' zstock_name = 'Vanguard FTSE All-World UCITS - (USD) Accumulating ETF' zstock_price = '153.25' zstock_changepct = '-0.0016' zstock_priceopen = '154.02' zstock_currency = 'EUR' zstock_closeyest = '153.49'
zstock_high = '154.17' )
            ( zstock_ticker = 'EPA:UBI' zstock_name = 'Ubisoft Entertainment SA' zstock_price = '4.84' zstock_changepct = '-0.027' zstock_priceopen = '4.86' zstock_currency = 'EUR' zstock_closeyest = '4.97' zstock_high = '4.9' )
            ( zstock_ticker = 'MSFT' zstock_name = 'Microsoft Corp' zstock_price = '424.82' zstock_changepct = '0.0005' zstock_priceopen = '422.38' zstock_currency = 'USD' zstock_closeyest = '424.62' zstock_high = '427.11' )
            ( zstock_ticker = 'NVDA' zstock_name = 'NVIDIA Corp' zstock_price = '216.61' zstock_changepct = '0.04' zstock_priceopen = '209.65' zstock_currency = 'USD' zstock_closeyest = '208.27' zstock_high = '216.83' )
            ( zstock_ticker = 'AAPL' zstock_name = 'Apple Inc' zstock_price = '267.62' zstock_changepct = '-0.0127' zstock_priceopen = '266.09' zstock_currency = 'USD' zstock_closeyest = '271.06' zstock_high = '268.36' )
            ( zstock_ticker = 'AMZN' zstock_name = 'Amazon.com Inc' zstock_price = '261.07' zstock_changepct = '-0.0111' zstock_priceopen = '263.46' zstock_currency = 'USD' zstock_closeyest = '263.99' zstock_high = '264.15' )
            ( zstock_ticker = 'META' zstock_name = 'Meta Platforms Inc' zstock_price = '678.62' zstock_changepct = '0.0053' zstock_priceopen = '671' zstock_currency = 'USD' zstock_closeyest = '675.03' zstock_high = '682.5' )
            ( zstock_ticker = 'AVGO' zstock_name = 'Broadcom Inc' zstock_price = '418.2' zstock_changepct = '-0.0108' zstock_priceopen = '420.48' zstock_currency = 'USD' zstock_closeyest = '422.76' zstock_high = '422.75' )
            ( zstock_ticker = 'GOOGL' zstock_name = 'Alphabet Inc Class A' zstock_price = '350.34' zstock_changepct = '0.0172' zstock_priceopen = '345.98' zstock_currency = 'USD' zstock_closeyest = '344.4' zstock_high = '353.18' )
            ( zstock_ticker = 'TSLA' zstock_name = 'Tesla Inc' zstock_price = '378.67' zstock_changepct = '0.0063' zstock_priceopen = '372.09' zstock_currency = 'USD' zstock_closeyest = '376.3' zstock_high = '380.78' )
            ( zstock_ticker = 'BRK.B' zstock_name = 'Berkshire Hathaway Inc Class B' zstock_price = '472.81' zstock_changepct = '0.0074' zstock_priceopen = '469.8' zstock_currency = 'USD' zstock_closeyest = '469.32' zstock_high = '475.5' )
            ( zstock_ticker = 'GOOG' zstock_name = 'Alphabet Inc Class C' zstock_price = '348.52' zstock_changepct = '0.0181' zstock_priceopen = '343.88' zstock_currency = 'USD' zstock_closeyest = '342.32' zstock_high = '350.9' )
            ( zstock_ticker = 'JPM' zstock_name = 'JPMorgan Chase & Co' zstock_price = '311.63' zstock_changepct = '0.0109' zstock_priceopen = '306.88' zstock_currency = 'USD' zstock_closeyest = '308.28' zstock_high = '312.58' )
            ( zstock_ticker = 'V' zstock_name = 'Visa Inc' zstock_price = '309.65' zstock_changepct = '0.0007' zstock_priceopen = '307.51' zstock_currency = 'USD' zstock_closeyest = '309.42' zstock_high = '310.82' )
            ( zstock_ticker = 'LLY' zstock_name = 'Eli Lilly And Co' zstock_price = '868.27' zstock_changepct = '-0.0177' zstock_priceopen = '878.13' zstock_currency = 'USD' zstock_closeyest = '883.96' zstock_high = '891.2' )
            ( zstock_ticker = 'NFLX' zstock_name = 'Netflix Inc' zstock_price = '91.36' zstock_changepct = '-0.0117' zstock_priceopen = '92.05' zstock_currency = 'USD' zstock_closeyest = '92.44' zstock_high = '92.84' )
            ( zstock_ticker = 'MA' zstock_name = 'Mastercard Inc' zstock_price = '506.43' zstock_changepct = '0.0045' zstock_priceopen = '500.76' zstock_currency = 'USD' zstock_closeyest = '504.17' zstock_high = '509.05' )
            ( zstock_ticker = 'COST' zstock_name = 'Costco Wholesale Corp' zstock_price = '998.01' zstock_changepct = '-0.013' zstock_priceopen = '1008.63' zstock_currency = 'USD' zstock_closeyest = '1011.15' zstock_high = '1014.41' )
            ( zstock_ticker = 'XOM' zstock_name = 'Exxon Mobil Corp' zstock_price = '148.19' zstock_changepct = '-0.0048' zstock_priceopen = '149.16' zstock_currency = 'USD' zstock_closeyest = '148.91' zstock_high = '151.18' )
            ( zstock_ticker = 'WMT' zstock_name = 'Walmart Inc' zstock_price = '127.59' zstock_changepct = '-0.0179' zstock_priceopen = '129.62' zstock_currency = 'USD' zstock_closeyest = '129.92' zstock_high = '129.81' )
            ( zstock_ticker = 'PG' zstock_name = 'Procter & Gamble Co' zstock_price = '148.4' zstock_changepct = '0.0015' zstock_priceopen = '147.42' zstock_currency = 'USD' zstock_closeyest = '148.18' zstock_high = '149.7' )
            ( zstock_ticker = 'JNJ' zstock_name = 'Johnson & Johnson' zstock_price = '225.34' zstock_changepct = '-0.0095' zstock_priceopen = '225.77' zstock_currency = 'USD' zstock_closeyest = '227.5' zstock_high = '227.91' )
            ( zstock_ticker = 'HD' zstock_name = 'Home Depot Inc' zstock_price = '332.3' zstock_changepct = '-0.0107' zstock_priceopen = '334.48' zstock_currency = 'USD' zstock_closeyest = '335.89' zstock_high = '337.38' )
            ( zstock_ticker = 'ABBV' zstock_name = 'AbbVie Common Stock' zstock_price = '197.38' zstock_changepct = '-0.0067' zstock_priceopen = '198' zstock_currency = 'USD' zstock_closeyest = '198.71' zstock_high = '201.42' )
            ( zstock_ticker = 'BAC' zstock_name = 'Bank of America Corp' zstock_price = '52.63' zstock_changepct = '0.0111' zstock_priceopen = '51.99' zstock_currency = 'USD' zstock_closeyest = '52.05' zstock_high = '52.93' )
            ( zstock_ticker = 'UNH' zstock_name = 'UnitedHealth Group Inc' zstock_price = '354.69' zstock_changepct = '-0.0006' zstock_priceopen = '353.91' zstock_currency = 'USD' zstock_closeyest = '354.92' zstock_high = '356.49' )
            ( zstock_ticker = 'KO' zstock_name = 'Coca-Cola Co' zstock_price = '75.44' zstock_changepct = '-0.0155' zstock_priceopen = '76.71' zstock_currency = 'USD' zstock_closeyest = '76.63' zstock_high = '76.71' )
            ( zstock_ticker = 'PM' zstock_name = 'Philip Morris International Inc.' zstock_price = '160.9' zstock_changepct = '-0.0201' zstock_priceopen = '163.05' zstock_currency = 'USD' zstock_closeyest = '164.2' zstock_high = '164.92' )
            ( zstock_ticker = 'CRM' zstock_name = 'Salesforce Inc' zstock_price = '180.18' zstock_changepct = '0.0113' zstock_priceopen = '178.26' zstock_currency = 'USD' zstock_closeyest = '178.16' zstock_high = '184.29' )
            ( zstock_ticker = 'ORCL' zstock_name = 'Oracle Corp' zstock_price = '172.96' zstock_changepct = '-0.0018' zstock_priceopen = '172.58' zstock_currency = 'USD' zstock_closeyest = '173.28' zstock_high = '173.55' )
            ( zstock_ticker = 'CSCO' zstock_name = 'Cisco Systems Inc' zstock_price = '88.26' zstock_changepct = '-0.0084' zstock_priceopen = '89.28' zstock_currency = 'USD' zstock_closeyest = '89.01' zstock_high = '89.5' )
            ( zstock_ticker = 'GE' zstock_name = 'General Electric Co' zstock_price = '284.56' zstock_changepct = '-0.0001' zstock_priceopen = '282.81' zstock_currency = 'USD' zstock_closeyest = '284.6' zstock_high = '284.87' )
            ( zstock_ticker = 'PLTR' zstock_name = 'Palantir Technologies Inc' zstock_price = '143.1' zstock_changepct = '0.0001' zstock_priceopen = '141.25' zstock_currency = 'USD' zstock_closeyest = '143.09' zstock_high = '145.07' )
            ( zstock_ticker = 'IBM' zstock_name = 'IBM Common Stock' zstock_price = '228.05' zstock_changepct = '-0.0169' zstock_priceopen = '229.95' zstock_currency = 'USD' zstock_closeyest = '231.98' zstock_high = '231.32' )
            ( zstock_ticker = 'WFC' zstock_name = 'Wells Fargo & Co' zstock_price = '80.56' zstock_changepct = '0.0144' zstock_priceopen = '79.39' zstock_currency = 'USD' zstock_closeyest = '79.42' zstock_high = '80.89' )
            ( zstock_ticker = 'ABT' zstock_name = 'Abbott Laboratories' zstock_price = '92.8' zstock_changepct = '0.0183' zstock_priceopen = '91.62' zstock_currency = 'USD' zstock_closeyest = '91.13' zstock_high = '93.26' )
            ( zstock_ticker = 'MCD' zstock_name = 'McDonald''s Corp' zstock_price = '290.21' zstock_changepct = '-0.0306' zstock_priceopen = '297.79' zstock_currency = 'USD' zstock_closeyest = '299.36' zstock_high = '298.53' )
            ( zstock_ticker = 'CVX' zstock_name = 'Chevron Corp' zstock_price = '184.78' zstock_changepct = '-0.0023' zstock_priceopen = '186.19' zstock_currency = 'USD' zstock_closeyest = '185.21' zstock_high = '188.37' )
            ( zstock_ticker = 'LIN' zstock_name = 'Linde PLC' zstock_price = '510.75' zstock_changepct = '0.0009' zstock_priceopen = '510.28' zstock_currency = 'USD' zstock_closeyest = '510.3' zstock_high = '512.96' )
            ( zstock_ticker = 'NOW' zstock_name = 'ServiceNow Inc' zstock_price = '90.45' zstock_changepct = '0.0031' zstock_priceopen = '89.06' zstock_currency = 'USD' zstock_closeyest = '90.17' zstock_high = '94.03' )
            ( zstock_ticker = 'DIS' zstock_name = 'Walt Disney Co' zstock_price = '102.35' zstock_changepct = '-0.0024' zstock_priceopen = '102.62' zstock_currency = 'USD' zstock_closeyest = '102.6' zstock_high = '103.81' )
            ( zstock_ticker = 'ACN' zstock_name = 'Accenture Plc' zstock_price = '176.97' zstock_changepct = '-0.0078' zstock_priceopen = '178' zstock_currency = 'USD' zstock_closeyest = '178.36' zstock_high = '181.94' )
            ( zstock_ticker = 'T' zstock_name = 'AT&T Inc' zstock_price = '25.52' zstock_changepct = '-0.026' zstock_priceopen = '26.33' zstock_currency = 'USD' zstock_closeyest = '26.2' zstock_high = '26.44' )
            ( zstock_ticker = 'ISRG' zstock_name = 'Intuitive Surgical Inc' zstock_price = '470.99' zstock_changepct = '-0.0233' zstock_priceopen = '481' zstock_currency = 'USD' zstock_closeyest = '482.22' zstock_high = '486.77' )
            ( zstock_ticker = 'MRK' zstock_name = 'Merck & Co Inc' zstock_price = '110.23' zstock_changepct = '-0.0149' zstock_priceopen = '111.22' zstock_currency = 'USD' zstock_closeyest = '111.9' zstock_high = '112.75' )
            ( zstock_ticker = 'UBER' zstock_name = 'Uber Technologies Inc' zstock_price = '76.27' zstock_changepct = '0.0218' zstock_priceopen = '74.68' zstock_currency = 'USD' zstock_closeyest = '74.64' zstock_high = '76.95' )
            ( zstock_ticker = 'GS' zstock_name = 'Goldman Sachs Group Inc' zstock_price = '937.81' zstock_changepct = '0.0118' zstock_priceopen = '926.04' zstock_currency = 'USD' zstock_closeyest = '926.91' zstock_high = '941.73' )
            ( zstock_ticker = 'INTU' zstock_name = 'Intuit Inc' zstock_price = '389.92' zstock_changepct = '-0.0152' zstock_priceopen = '390.05' zstock_currency = 'USD' zstock_closeyest = '395.95' zstock_high = '398.99' )
            ( zstock_ticker = 'VZ' zstock_name = 'Verizon Communications Inc' zstock_price = '47.1' zstock_changepct = '0.0155' zstock_priceopen = '47.43' zstock_currency = 'USD' zstock_closeyest = '46.38' zstock_high = '48.65' )
            ( zstock_ticker = 'AMD' zstock_name = 'Advanced Micro Devices Inc' zstock_price = '334.49' zstock_changepct = '-0.0383' zstock_priceopen = '346.32' zstock_currency = 'USD' zstock_closeyest = '347.8' zstock_high = '349.21' )
            ( zstock_ticker = 'ADBE' zstock_name = 'Adobe Inc' zstock_price = '239.31' zstock_changepct = '-0.025' zstock_priceopen = '240.77' zstock_currency = 'USD' zstock_closeyest = '245.44' zstock_high = '245.88' )
            ( zstock_ticker = 'RTX' zstock_name = 'Rtx Corp' zstock_price = '173.38' zstock_changepct = '-0.005' zstock_priceopen = '172.3' zstock_currency = 'USD' zstock_closeyest = '174.26' zstock_high = '176.99' )
            ( zstock_ticker = 'PEP' zstock_name = 'PepsiCo Inc' zstock_price = '154.1' zstock_changepct = '-0.0086' zstock_priceopen = '155.53' zstock_currency = 'USD' zstock_closeyest = '155.44' zstock_high = '156.65' )
            ( zstock_ticker = 'BKNG' zstock_name = 'Booking Holdings Inc' zstock_price = '177.49' zstock_changepct = '-0.0154' zstock_priceopen = '178.29' zstock_currency = 'USD' zstock_closeyest = '180.28' zstock_high = '181.47' )
            ( zstock_ticker = 'TXN' zstock_name = 'Texas Instruments Inc' zstock_price = '269.5' zstock_changepct = '-0.0276' zstock_priceopen = '276.17' zstock_currency = 'USD' zstock_closeyest = '277.14' zstock_high = '277.02' )
            ( zstock_ticker = 'QCOM' zstock_name = 'Qualcomm Inc' zstock_price = '150.26' zstock_changepct = '0.0095' zstock_priceopen = '156.31' zstock_currency = 'USD' zstock_closeyest = '148.85' zstock_high = '161' )
            ( zstock_ticker = 'PGR' zstock_name = 'Progressive Corp' zstock_price = '201.98' zstock_changepct = '0.0054' zstock_priceopen = '199.37' zstock_currency = 'USD' zstock_closeyest = '200.89' zstock_high = '204.42' )
            ( zstock_ticker = 'CAT' zstock_name = 'Caterpillar Inc' zstock_price = '828.79' zstock_changepct = '-0.0024' zstock_priceopen = '829.76' zstock_currency = 'USD' zstock_closeyest = '830.79' zstock_high = '836.02' )
            ( zstock_ticker = 'SPGI' zstock_name = 'S&P Global Inc' zstock_price = '437.22' zstock_changepct = '0.001' zstock_priceopen = '436.75' zstock_currency = 'USD' zstock_closeyest = '436.79' zstock_high = '439.82' )
            ( zstock_ticker = 'AXP' zstock_name = 'American Express Co' zstock_price = '318.84' zstock_changepct = '0.0152' zstock_priceopen = '313.02' zstock_currency = 'USD' zstock_closeyest = '314.08' zstock_high = '318.96' )
            ( zstock_ticker = 'MS' zstock_name = 'Morgan Stanley' zstock_price = '190.18' zstock_changepct = '0.0112' zstock_priceopen = '187.87' zstock_currency = 'USD' zstock_closeyest = '188.07' zstock_high = '190.59' )
            ( zstock_ticker = 'BSX' zstock_name = 'Boston Scientific Corp' zstock_price = '59.95' zstock_changepct = '-0.0342' zstock_priceopen = '61.21' zstock_currency = 'USD' zstock_closeyest = '62.07' zstock_high = '61.73' )
            ( zstock_ticker = 'BA' zstock_name = 'Boeing Co' zstock_price = '231.33' zstock_changepct = '-0.0048' zstock_priceopen = '233' zstock_currency = 'USD' zstock_closeyest = '232.44' zstock_high = '235.45' )
            ( zstock_ticker = 'TMO' zstock_name = 'Thermo Fisher Scientific Inc' zstock_price = '468.04' zstock_changepct = '-0.0036' zstock_priceopen = '462.66' zstock_currency = 'USD' zstock_closeyest = '469.71' zstock_high = '475.21' )
            ( zstock_ticker = 'SCHW' zstock_name = 'Charles Schwab Corporation Common Stock' zstock_price = '90.76' zstock_changepct = '0.0255' zstock_priceopen = '88.26' zstock_currency = 'USD' zstock_closeyest = '88.5' zstock_high = '91.12' )
            ( zstock_ticker = 'TJX' zstock_name = 'TJX Companies Inc' zstock_price = '157.48' zstock_changepct = '0.0029' zstock_priceopen = '156.47' zstock_currency = 'USD' zstock_closeyest = '157.03' zstock_high = '158.77' )
            ( zstock_ticker = 'NEE' zstock_name = 'NextEra Energy Inc' zstock_price = '94.83' zstock_changepct = '-0.0047' zstock_priceopen = '95.86' zstock_currency = 'USD' zstock_closeyest = '95.28' zstock_high = '96.9' )
            ( zstock_ticker = 'AMGN' zstock_name = 'Amgen Inc' zstock_price = '340.15' zstock_changepct = '-0.0128' zstock_priceopen = '342.35' zstock_currency = 'USD' zstock_closeyest = '344.55' zstock_high = '348.04' )
            ( zstock_ticker = 'HON' zstock_name = 'Honeywell International Inc' zstock_price = '212.05' zstock_changepct = '-0.0052' zstock_priceopen = '213.36' zstock_currency = 'USD' zstock_closeyest = '213.16' zstock_high = '214.13' )
            ( zstock_ticker = 'BLK' zstock_name = 'BlackRock Inc' zstock_price = '1056.86' zstock_changepct = '0.0114' zstock_priceopen = '1040.85' zstock_currency = 'USD' zstock_closeyest = '1044.97' zstock_high = '1058.5' )
            ( zstock_ticker = 'C' zstock_name = 'Citigroup Inc' zstock_price = '129.14' zstock_changepct = '0.0091' zstock_priceopen = '127.86' zstock_currency = 'USD' zstock_closeyest = '127.98' zstock_high = '129.4' )
            ( zstock_ticker = 'UNP' zstock_name = 'Union Pacific Corp' zstock_price = '268.91' zstock_changepct = '0.0008' zstock_priceopen = '269.45' zstock_currency = 'USD' zstock_closeyest = '268.7' zstock_high = '270.82' )
            ( zstock_ticker = 'GILD' zstock_name = 'Gilead Sciences Inc' zstock_price = '127.75' zstock_changepct = '-0.0203' zstock_priceopen = '128.8' zstock_currency = 'USD' zstock_closeyest = '130.4' zstock_high = '130.33' )
            ( zstock_ticker = 'CMCSA' zstock_name = 'Comcast Corp' zstock_price = '27.51' zstock_changepct = '-0.0002' zstock_priceopen = '27.45' zstock_currency = 'USD' zstock_closeyest = '27.52' zstock_high = '28.01' )
            ( zstock_ticker = 'AMAT' zstock_name = 'Applied Materials Inc' zstock_price = '404.86' zstock_changepct = '-0.0294' zstock_priceopen = '416' zstock_currency = 'USD' zstock_closeyest = '417.11' zstock_high = '417' )
            ( zstock_ticker = 'ADP' zstock_name = 'Automatic Data Processing Inc' zstock_price = '197.23' zstock_changepct = '0.0036' zstock_priceopen = '195.85' zstock_currency = 'USD' zstock_closeyest = '196.53' zstock_high = '199.45' )
            ( zstock_ticker = 'PFE' zstock_name = 'Pfizer Inc' zstock_price = '26.79' zstock_changepct = '-0.0078' zstock_priceopen = '27.06' zstock_currency = 'USD' zstock_closeyest = '27' zstock_high = '27.35' )
            ( zstock_ticker = 'SYK' zstock_name = 'Stryker Corp' zstock_price = '329.01' zstock_changepct = '0.0046' zstock_priceopen = '326.59' zstock_currency = 'USD' zstock_closeyest = '327.51' zstock_high = '330.94' )
            ( zstock_ticker = 'DE' zstock_name = 'Deere & Co' zstock_price = '567.69' zstock_changepct = '0.009' zstock_priceopen = '566.63' zstock_currency = 'USD' zstock_closeyest = '562.64' zstock_high = '577.99' )
            ( zstock_ticker = 'LOW' zstock_name = 'Lowe''s Companies Inc' zstock_price = '242.55' zstock_changepct = '-0.0078' zstock_priceopen = '243.35' zstock_currency = 'USD' zstock_closeyest = '244.45' zstock_high = '246.88' )
            ( zstock_ticker = 'ETN' zstock_name = 'Eaton Corporation PLC' zstock_price = '416.77' zstock_changepct = '-0.0169' zstock_priceopen = '425.4' zstock_currency = 'USD' zstock_closeyest = '423.92' zstock_high = '426.38' )
            ( zstock_ticker = 'GEV' zstock_name = 'GE Vernova Inc' zstock_price = '1120.23' zstock_changepct = '-0.0252' zstock_priceopen = '1135.23' zstock_currency = 'USD' zstock_closeyest = '1149.19' zstock_high = '1140' )
            ( zstock_ticker = 'PANW' zstock_name = 'Palo Alto Networks Inc' zstock_price = '182.9' zstock_changepct = '0.0244' zstock_priceopen = '176.86' zstock_currency = 'USD' zstock_closeyest = '178.54' zstock_high = '184.02' )
            ( zstock_ticker = 'DHR' zstock_name = 'Danaher Corp' zstock_price = '180.62' zstock_changepct = '0.019' zstock_priceopen = '176.76' zstock_currency = 'USD' zstock_closeyest = '177.25' zstock_high = '181.45' )
            ( zstock_ticker = 'COF' zstock_name = 'Capital One Financial Corp' zstock_price = '194.11' zstock_changepct = '0.0142' zstock_priceopen = '190.93' zstock_currency = 'USD' zstock_closeyest = '191.39' zstock_high = '194.8' )
            ( zstock_ticker = 'TMUS' zstock_name = 'T-Mobile Us Inc' zstock_price = '182.75' zstock_changepct = '-0.0371' zstock_priceopen = '188.76' zstock_currency = 'USD' zstock_closeyest = '189.8' zstock_high = '190.47' )
            ( zstock_ticker = 'MMC' zstock_name = 'NA' zstock_price = '0' zstock_changepct = '0' zstock_priceopen = '0' zstock_currency = 'NA' zstock_closeyest = '0' zstock_high = '0' )
            ( zstock_ticker = 'VRTX' zstock_name = 'Vertex Pharmaceuticals Inc' zstock_price = '426.01' zstock_changepct = '-0.0104' zstock_priceopen = '427.01' zstock_currency = 'USD' zstock_closeyest = '430.5' zstock_high = '434.07' )
            ( zstock_ticker = 'COP' zstock_name = 'ConocoPhillips' zstock_price = '121.68' zstock_changepct = '-0.0007' zstock_priceopen = '122.21' zstock_currency = 'USD' zstock_closeyest = '121.76' zstock_high = '123.65' )
            ( zstock_ticker = 'ADI' zstock_name = 'Analog Devices Inc' zstock_price = '392.59' zstock_changepct = '-0.0175' zstock_priceopen = '398.29' zstock_currency = 'USD' zstock_closeyest = '399.57' zstock_high = '399.52' )
            ( zstock_ticker = 'MDT' zstock_name = 'Medtronic PLC' zstock_price = '82.92' zstock_changepct = '-0.0048' zstock_priceopen = '83.12' zstock_currency = 'USD' zstock_closeyest = '83.32' zstock_high = '84.05' )
            ( zstock_ticker = 'CB' zstock_name = 'Chubb Limited' zstock_price = '324.6' zstock_changepct = '-0.0047' zstock_priceopen = '323.48' zstock_currency = 'USD' zstock_closeyest = '326.12' zstock_high = '329.93' )
    ).

    MODIFY zstock_data_fin FROM TABLE @stock_full_data.

    IF sy-subrc <> 0.
        out->write( 'Error when loading data.' ).
    ELSE.
            out->write( |Count: { sy-dbcnt }| ).
    ENDIF.

    DATA: stock_rating_data TYPE TABLE OF zstock_data_rat.
    stock_rating_data = VALUE #(
            ( zstock_ticker = 'LON:CSPX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AMS:VWCE' zstock_rating = 'Buy' )
            ( zstock_ticker = 'EPA:UBI' zstock_rating = 'Hold' )
            ( zstock_ticker = 'MSFT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'NVDA' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AAPL' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AMZN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'META' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AVGO' zstock_rating = 'Buy' )
            ( zstock_ticker = 'GOOGL' zstock_rating = 'Buy' )
            ( zstock_ticker = 'TSLA' zstock_rating = 'Hold' )
            ( zstock_ticker = 'BRK.B' zstock_rating = 'Buy' )
            ( zstock_ticker = 'GOOG' zstock_rating = 'Buy' )
            ( zstock_ticker = 'JPM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'V' zstock_rating = 'Buy' )
            ( zstock_ticker = 'LLY' zstock_rating = 'Buy' )
            ( zstock_ticker = 'NFLX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'MA' zstock_rating = 'Buy' )
            ( zstock_ticker = 'COST' zstock_rating = 'Buy' )
            ( zstock_ticker = 'XOM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'WMT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PG' zstock_rating = 'Buy' )
            ( zstock_ticker = 'JNJ' zstock_rating = 'Buy' )
            ( zstock_ticker = 'HD' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ABBV' zstock_rating = 'Hold' )
            ( zstock_ticker = 'BAC' zstock_rating = 'Buy' )
            ( zstock_ticker = 'UNH' zstock_rating = 'Buy' )
            ( zstock_ticker = 'KO' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'CRM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ORCL' zstock_rating = 'Buy' )
            ( zstock_ticker = 'CSCO' zstock_rating = 'Buy' )
            ( zstock_ticker = 'GE' zstock_rating = 'Hold' )
            ( zstock_ticker = 'PLTR' zstock_rating = 'Hold' )
            ( zstock_ticker = 'IBM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'WFC' zstock_rating = 'Hold' )
            ( zstock_ticker = 'ABT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'MCD' zstock_rating = 'Buy' )
            ( zstock_ticker = 'CVX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'LIN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'NOW' zstock_rating = 'Buy' )
            ( zstock_ticker = 'DIS' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ACN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'T' zstock_rating = 'Hold' )
            ( zstock_ticker = 'ISRG' zstock_rating = 'Buy' )
            ( zstock_ticker = 'MRK' zstock_rating = 'Buy' )
            ( zstock_ticker = 'UBER' zstock_rating = 'Hold' )
            ( zstock_ticker = 'GS' zstock_rating = 'Hold' )
            ( zstock_ticker = 'INTU' zstock_rating = 'Buy' )
            ( zstock_ticker = 'VZ' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AMD' zstock_rating = 'Hold' )
            ( zstock_ticker = 'ADBE' zstock_rating = 'Buy' )
            ( zstock_ticker = 'RTX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PEP' zstock_rating = 'Buy' )
            ( zstock_ticker = 'BKNG' zstock_rating = 'Buy' )
            ( zstock_ticker = 'TXN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'QCOM' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PGR' zstock_rating = 'Buy' )
            ( zstock_ticker = 'CAT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'SPGI' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AXP' zstock_rating = 'Hold' )
            ( zstock_ticker = 'MS' zstock_rating = 'Buy' )
            ( zstock_ticker = 'BSX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'BA' zstock_rating = 'Buy' )
            ( zstock_ticker = 'TMO' zstock_rating = 'Buy' )
            ( zstock_ticker = 'SCHW' zstock_rating = 'Buy' )
            ( zstock_ticker = 'TJX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'NEE' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AMGN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'HON' zstock_rating = 'Buy' )
            ( zstock_ticker = 'BLK' zstock_rating = 'Buy' )
            ( zstock_ticker = 'C' zstock_rating = 'Buy' )
            ( zstock_ticker = 'UNP' zstock_rating = 'Buy' )
            ( zstock_ticker = 'GILD' zstock_rating = 'Hold' )
            ( zstock_ticker = 'CMCSA' zstock_rating = 'Buy' )
            ( zstock_ticker = 'AMAT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ADP' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PFE' zstock_rating = 'Buy' )
            ( zstock_ticker = 'SYK' zstock_rating = 'Buy' )
            ( zstock_ticker = 'DE' zstock_rating = 'Buy' )
            ( zstock_ticker = 'LOW' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ETN' zstock_rating = 'Buy' )
            ( zstock_ticker = 'GEV' zstock_rating = 'Buy' )
            ( zstock_ticker = 'PANW' zstock_rating = 'Buy' )
            ( zstock_ticker = 'DHR' zstock_rating = 'Buy' )
            ( zstock_ticker = 'COF' zstock_rating = 'Buy' )
            ( zstock_ticker = 'TMUS' zstock_rating = 'Buy' )
            ( zstock_ticker = 'MMC' zstock_rating = 'Buy' )
            ( zstock_ticker = 'VRTX' zstock_rating = 'Buy' )
            ( zstock_ticker = 'COP' zstock_rating = 'Buy' )
            ( zstock_ticker = 'ADI' zstock_rating = 'Buy' )
            ( zstock_ticker = 'MDT' zstock_rating = 'Buy' )
            ( zstock_ticker = 'CB' zstock_rating = 'Buy' )
    ).
    MODIFY zstock_data_rat FROM TABLE @stock_rating_data.

    IF sy-subrc <> 0.
        out->write( 'Error when loading data.' ).
    ELSE.
        out->write( |Count: { sy-dbcnt }| ).
    ENDIF.

  ENDMETHOD.
ENDCLASS.
